### ISSUE TITLE
How install ionCube Loader

### ISSUE THREAD

**Issue by MFakhrani** [liara-cloud/laravel-getting-started#28]
Hey guys
How can I automate the installation of ionCube Loader using the liara_pre_build.sh script, ensuring it's correctly configured as the first extension in the php.ini file?

**Comment by eyeamnoob** [comment]
Hello,
This extension comes pre-installed on all PHP versions except 8.3. It wasn't available for PHP 8.3 until recently. We may consider adding it to PHP 8.3 in the future.
